### ISSUE TITLE
Multishot still on loot tables

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/RTTS-Atum#52]
![2019-05-20_19 32 15](https://user-images.githubusercontent.com/50718369/58058226-04c54b80-7b36-11e9-9db8-90fd5153358b.png)
Found in a pyramid I think? Might have been a random chest, I didn't remember it was a banned enchant til I got back and started sorting from a long pyramid run.

**Comment by Shadowclaimer** [comment]
You're positive this isn't one we had before and you looted it during pyramids?

**Comment by Azuriuz** [comment]
Yes, I emptied my inventory as I do every time before a pyramid run. This book was either gotten from a ruin loot table, or a pyramid loot table. Might have been from the sarcophogi as well but it's 100% from one of the loot tables for chests, sarcophogi, or crates

**Comment by Shadowclaimer** [comment]
After much testing in singleplayer I think this was a config fluke for a portion there when all enchants were available.

I can't find books with vorpal or multishot after testing over 200 spawned pharaoh chests.

If this bug resurfaces in future testing let me know, but the server might be a bad test bed because of this (since pyramids or ruins spawned during the config hiccup will still have those books.)
