### ISSUE TITLE
Chisel and bits bag can't be crafted.

### ISSUE THREAD

**Issue by sscards55** [TeamMetallurgy/RTTS-Atum#54]
The recipe included in the scripts is not working.

**Comment by Azuriuz** [comment]
it should be a single bit, surrounded by linen blocks. (the old recipe was wool instead of linen, so try both so shadow knows which recipe isn't working please)

**Comment by Shadowclaimer** [comment]
Linen cloth not blocks

**Comment by sscards55** [comment]
![2019-05-21_19 23 01](https://user-images.githubusercontent.com/5591207/58142966-f0e51c80-7bfd-11e9-92cc-eea270ed3cec.png)

**Comment by Azuriuz** [comment]
I also tested wool and linen block, no dice. NEI reads the recipe correctly, as 8 linen cloth and 1 bit; but it doesn't work. Not sure if this is because it stopped reading atum bits, or because the recipe doesn't work.
I think it's the latter, as autocraft button does place both atum bits, and the bolts of linen cloth.
